-- def -> type var = a
int a = 1;
bool b = true;
bool c = false;
string str = "hello";
int list l1 = [1,2,3];
bool list l2 = [true, false, true, true];
int list list l3 = [[1,2], [3,4], [5,6]];
unit u = ();
