clean: 
	cd ./tests/codegen; \
	rm -f *.out *.ast *.cast *.last *.ll *.s *.exe; \
	cd ../scanparse; \
	rm -f *.ast *.cast *.last *.ll *.s *.exe *.out *.trimmed; \
	cd ../test_suite/positive_test;\
	rm -f *.out;\
	cd ../negative_test;\
	rm -f *.out;\
	cd ../../case;\
	rm -f *.trimmed *.out;\