println 1 + 1;
println 1 * 1; 
println 20 - 30;
println 10 / 2;
println 5 % 2;
println 5 > 2;
println 2 > 5;
println true == true;
println true != false;
println "hello" == "hello";
println "you" == "me";
println "hi" != "hello";
println 3 == (let x = 3 in x);
println ((5+7) != (5+7));
println 4 != 5;
println () == ();
